#
# The name of the hardcore world
HardcoreWorldName: W_Hardcore
#
# The number of hours that a player is banned when he/she has died in the hardcore world
BannedFromWorldHours: 1
#
# BannedUntilMessage has 1 parameter: <banned for hours> (%d)
BannedUntilMessage: Due to dying in the hardcore world, you have now been banned from this world for %d hours.
#
# StillBannedHoursMessage has 2 parameters: <hours left> (%d), <minutes left> (%d)
StillBannedHoursMessage: Due to your earlier death in the hardcore world, you are banned for another %d hours and %d minutes.
#
# StillBannedMinutesMessage has 1 parameters: <minutes left> (%d)
StillBannedMinutesMessage: Due to your earlier death in the hardcore world, you are banned for another %d minutes more.
#
# TeleportToSpawnCommand has 0 parameters
TeleportToSpawnCommand: /spawn
#
# DoDebugPrint
DoDebugPrint: 0

